name: Jakarta Config Build

on:
    push:
        paths-ignore:
            - '.gitattributes'
            - '.gitignore'
            - 'CONTRIBUTING*'
            - 'KEYS'
            - 'LICENSE'
            - 'NOTICE'
            - 'README*'
    pull_request:
        paths-ignore:
            - '.gitattributes'
            - '.gitignore'
            - 'CONTRIBUTING*'
            - 'KEYS'
            - 'LICENSE'
            - 'NOTICE'
            - 'README*'

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ 11, 17 ]
        name: build with jdk ${{matrix.java}}

        steps:
            -   uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
                name: checkout
                with:
                    ref: ${{ github.event.pull_request.merge_commit_sha }}

            -   uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
                name: set up jdk ${{matrix.java}}
                with:
                    distribution: 'temurin'
                    java-version: ${{matrix.java}}
                    cache: 'maven'

            - name: build with maven
              run: mvn --batch-mode --no-transfer-progress --show-version --errors install
