name: Jakarta Config Build

on:
    push:
        paths-ignore:
            - '.gitattributes'
            - '.gitignore'
            - 'CONTRIBUTING*'
            - 'KEYS'
            - 'LICENSE'
            - 'NOTICE'
            - 'README*'
    pull_request:
        paths-ignore:
            - '.gitattributes'
            - '.gitignore'
            - 'CONTRIBUTING*'
            - 'KEYS'
            - 'LICENSE'
            - 'NOTICE'
            - 'README*'

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ 11, 17 ]
        name: build with jdk ${{matrix.java}}

        steps:
            -   uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
                name: checkout
                with:
                    ref: ${{ github.event.pull_request.merge_commit_sha }}

            -   uses: actions/setup-java@v3.12.0
                name: set up jdk ${{matrix.java}}
                with:
                    distribution: 'temurin'
                    java-version: ${{matrix.java}}
                    cache: 'maven'

            - name: build with maven
              run: mvn --batch-mode --no-transfer-progress --show-version --errors install
